import React from 'react';
import { Building2, Calendar, FileText, User } from 'lucide-react';
import { format } from 'date-fns';

export default function PrintLayout({ children, title, dateRange, totalEntries }) {
  return (
    <div className="bg-white relative min-h-[297mm] flex flex-col font-sans">
      {/* Premium Header - Based on user image */}
      <div className="bg-[#f0f7ff] p-6 border-b border-blue-100 flex items-center gap-5">
        <div className="w-16 h-16 bg-white rounded-xl shadow-sm border border-blue-50 flex items-center justify-center shrink-0">
          <Building2 className="w-10 h-10 text-blue-600" />
        </div>
        <div className="flex-1">
          <h1 className="text-2xl font-black text-blue-900 tracking-tight leading-none mb-2">
            Makhdoomiyya's Business Report
          </h1>
          <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-[11px] text-blue-800/60 font-semibold uppercase tracking-wider">
            <div className="flex items-center gap-1.5">
              <Calendar size={12} className="text-blue-400" />
              <span>Generated On - {format(new Date(), 'dd MMM yyyy, hh:mm a')}</span>
            </div>
            <div className="flex items-center gap-1.5">
              <User size={12} className="text-blue-400" />
              <span>Generated by - Makhdoomiyya (+919496413786)</span>
            </div>
          </div>
        </div>
      </div>

      {/* Main Body Area */}
      <div className="p-10 flex-1 flex flex-col">
        {/* Report Identification */}
        <div className="mb-8">
          <h2 className="text-xl font-bold text-slate-800 uppercase tracking-tight mb-4">
            {title || 'Category-wise summary'}
          </h2>
          
          <div className="bg-white border border-slate-200 rounded-md p-4 mb-4 shadow-sm">
            <div className="flex items-center gap-2 text-sm font-bold text-slate-700">
              <span className="text-slate-400">Duration:</span>
              <span>{dateRange || 'Full Period'}</span>
            </div>
          </div>
          
          {totalEntries !== undefined && (
            <div className="text-sm font-bold text-slate-500 mb-6 px-1">
              Total No. of entries: <span className="text-slate-800">{totalEntries}</span>
            </div>
          )}
        </div>

        {/* Content */}
        <div className="flex-1">
          {children}
        </div>

        {/* Footer */}
        <div className="mt-12 pt-8 border-t border-slate-100 flex justify-between items-end">
          <div className="text-[10px] text-slate-400 font-medium italic">
            <p>This is an automated financial report generated by Makhdoomiyya Accounts System.</p>
          </div>
          
          <div className="flex flex-col items-center">
             <div className="w-32 h-1 border-t-2 border-slate-800 mb-2"></div>
             <p className="text-[10px] font-bold text-slate-800 uppercase tracking-widest">Seal & Signature</p>
          </div>
        </div>
      </div>
    </div>
  );
}
